version: '3'

services:

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 7000:15672
      - 7001:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

  transactions-db:
    image: postgres
    container_name: transactions-db
    environment:
      POSTGRES_PASSWORD: ${TRANSACTIONS_DB_PASSWORD}
      POSTGRES_USER: ${TRANSACTIONS_DB_USER}
      POSTGRES_DB: ${TRANSACTIONS_DB}
    ports:
      - 5442:5432

  transactions-service:
    depends_on:
      - transactions-db
      - rabbitmq
    links:
      - transactions-db
    container_name: transactions-service
    build: ./services/transactions
    ports:
      - 3010:3000
    volumes:
      - ./services/transactions/src:/usr/src/app/src
    working_dir: /usr/src/app/src
    environment:
      POSTGRES_PASSWORD: ${TRANSACTIONS_DB_PASSWORD}
      POSTGRES_USER: ${TRANSACTIONS_DB_USER}
      POSTGRES_DB: ${TRANSACTIONS_DB}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    command: nodemon app.js

  recommendations-db:
    container_name: recommendations-db
    image: mongo
    restart: always
    ports:
      - 27017:27017

  recommendations-service:
    depends_on:
      - recommendations-db
      - rabbitmq
    links:
      - recommendations-db
    container_name: recommendations-service
    build: ./services/recommendations
    ports:
      - 3000:3000
    volumes:
      - ./services/recommendations/src:/usr/src/app/src
    working_dir: /usr/src/app/src
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    command: nodemon app.js

  generator-db:
    image: postgres
    container_name: generator-db
    environment:
      POSTGRES_PASSWORD: ${GENERATOR_DB_PASSWORD}
      POSTGRES_USER: ${GENERATOR_DB_USER}
      POSTGRES_DB: ${GENERATOR_DB}
    ports:
      - 5433:5432

  generator-service:
    depends_on:
      - generator-db
      - rabbitmq
    links:
      - generator-db
    container_name: generator-service
    build: ./services/generator
    ports:
      - 5000:5000
    volumes:
      - ./services/generator/src:/usr/src/app/src
    environment:
      POSTGRES_PASSWORD: ${GENERATOR_DB_PASSWORD}
      POSTGRES_USER: ${GENERATOR_DB_USER}
      POSTGRES_DB: ${GENERATOR_DB}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    working_dir: /usr/src/app/src
    command: nodemon app.py