version: '3.1'

services:

  recommendations-db:
    image: postgres
    container_name: recommendations-db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5432:5432

  recommendations-service:
    depends_on:
      - recommendations-db
      - generator-service
    links:
      - recommendations-db
      - generator-service
    build: ./services/recommendations
    ports:
      - 3000:3000
    volumes:
      - ./services/recommendations:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev

  generator-db:
    image: postgres
    container_name: generator-db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5433:5432

  generator-service:
    depends_on:
      - generator-db
    links:
      - generator-db
    build: ./services/generator
    ports:
      - 5000:5000
    volumes:
      - ./services/generator:/usr/src/app
    working_dir: /usr/src/app/src
    command: nodemon app.py